# Generated by Django 4.2.5 on 2023-10-27 12:33

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_link', models.ImageField(upload_to='brand/')),
            ],
        ),
        migrations.CreateModel(
            name='Featured_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='featured_image/')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Featured_category',
                'verbose_name_plural': 'Featured_categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.IntegerField()),
                ('discounted_price', models.FloatField()),
                ('offer_percent', models.CharField(blank=True, help_text='this can be blank', max_length=20)),
                ('img', models.ImageField(upload_to='project_images/')),
                ('in_stock', models.IntegerField()),
                ('availabe', models.BooleanField(default=True)),
                ('model', models.CharField(default='No model', max_length=30)),
                ('feature_product', models.CharField(blank=True, choices=[('new arrival', 'new arrival'), ('new arrival gadget', 'new arrival gadget'), ('deal of the day', 'deal of the day'), ('best deal', 'best deal'), ('best sellers', 'best sellers')], help_text='this can be blank', max_length=200)),
                ('created_date', models.DateField(auto_now_add=True, help_text='this can be blank')),
                ('Product_information', ckeditor.fields.RichTextField()),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('brand', models.ForeignKey(blank=True, default='No brand', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('featured_category', models.ForeignKey(blank=True, help_text='this can be blank', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.featured_category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
    ]
