# Generated by Django 4.2.5 on 2023-11-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.CharField(blank=True, default=1, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
