# Generated by Django 4.2.5 on 2023-10-27 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=150)),
                ('quanity', models.PositiveIntegerField(default=1)),
                ('price', models.FloatField(default=0)),
                ('category', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.cart')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=150)),
                ('order_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('division', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('quantity', models.PositiveIntegerField()),
                ('payment_method', models.CharField(default='Cash On', max_length=100)),
                ('transaction_number', models.CharField(default='01', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('total_price', models.FloatField(default=0)),
                ('devliv_charge', models.PositiveIntegerField(default=120)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('On The Way', 'On The Way'), ('Deliverd', 'Deliverd')], default='pending', max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('orderd_products', models.ManyToManyField(to='payment.orderitem')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
