# Generated by Django 4.2.5 on 2023-10-29 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_orderitem_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery_info',
            old_name='payment_method',
            new_name='payment',
        ),
        migrations.RemoveField(
            model_name='delivery_info',
            name='devliv_charge',
        ),
    ]
