# Generated by Django 4.2.5 on 2023-10-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rename_payment_method_delivery_info_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_info',
            name='devliv_charge',
            field=models.PositiveIntegerField(default=120),
        ),
    ]
