# Generated by Django 4.2.5 on 2023-10-29 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('payment', '0004_delivery_info_devliv_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cart.cart'),
        ),
    ]
